#!/usr/bin/env bash
# A Git command for checking the status of all your repos at once.

#This initial version will assume that all the repositories are children 
# of a single parent directory, and that the PWD is that directory.

for dir in `ls`
    do
        echo $dir
        cd $dir
        git pull
        cd ..
done
